"""
Append batch-02 entries to v1/data.json.
Raises the registry from 60 to 100 entries.

Rules followed:
- Each entry's core fields (product_name, company, cancer_types, modality, general
  intended_use) are populated from widely-documented public sources.
- fda_decision_date, fda_pathway, and clinical_evidence performance metrics are
  set only where the curator has high confidence; otherwise null.
- Every entry has at least one `sources` entry pointing to a company product page
  or the FDA 510(k) public database, with date_accessed = 2026-04-20.
- Any entry the curator would not yet stake a peer-reviewed claim on is flagged
  in NEEDS_VERIFICATION.md in the registry root; Ahmed reviews before the July
  press push (tracker task 1.6).

Run from registry root:  python3 scripts/add_batch_02_entries.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "v1" / "data.json"

TODAY = "2026-04-20"
FDA_510K_SEARCH = "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm"


def src(url, type_="company"):
    return {"type": type_, "url": url, "date_accessed": TODAY}


NEW_ENTRIES = [
    # ---------- Histopathology additions ----------
    {
        "id": "paige-breast",
        "product_name": "Paige Breast",
        "company": "Paige.AI",
        "company_url": "https://www.paige.ai/",
        "cancer_types": ["breast"],
        "modality": "histopathology",
        "intended_use": "AI-assisted detection and characterization of invasive breast carcinoma and ductal carcinoma in situ on H&E-stained whole-slide images.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.paige.ai/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "pathai-aisight-dx",
        "product_name": "AISight Dx",
        "company": "PathAI",
        "company_url": "https://www.pathai.com/",
        "cancer_types": ["solid_tumor"],
        "modality": "histopathology",
        "intended_use": "AI-powered digital pathology platform with clinical-grade applications including PD-L1, HER2, and tumor cellularity quantification, deployed across clinical and research sites.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.pathai.com/aisight/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "deepbio-deepdx-prostate",
        "product_name": "DeepDx Prostate",
        "company": "DeepBio",
        "company_url": "https://www.deep.bio/",
        "cancer_types": ["prostate"],
        "modality": "histopathology",
        "intended_use": "AI-based prostate cancer detection and Gleason grading on H&E whole-slide images of core needle biopsies.",
        "regulatory": {
            "fda_status": "De Novo authorized",
            "fda_pathway": "de_novo",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU", "KR"]},
        "sources": [src("https://www.deep.bio/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "contextvision-inify-prostate",
        "product_name": "INIFY Prostate",
        "company": "ContextVision",
        "company_url": "https://www.contextvision.com/",
        "cancer_types": ["prostate"],
        "modality": "histopathology",
        "intended_use": "AI-based detection and Gleason grading assistance for prostate core needle biopsies.",
        "regulatory": {
            "fda_status": "Research Use",
            "fda_pathway": "research_use",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU"]},
        "sources": [src("https://www.contextvision.com/products/inify-prostate-screening")],
    },
    {
        "id": "aiforia-clinical-prostate",
        "product_name": "Aiforia Clinical Prostate",
        "company": "Aiforia Technologies",
        "company_url": "https://www.aiforia.com/",
        "cancer_types": ["prostate"],
        "modality": "histopathology",
        "intended_use": "Clinical-grade AI for prostate cancer detection and Gleason grading on H&E whole-slide images.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.aiforia.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "aiforia-her2",
        "product_name": "Aiforia Clinical HER2 Breast",
        "company": "Aiforia Technologies",
        "company_url": "https://www.aiforia.com/",
        "cancer_types": ["breast"],
        "modality": "histopathology",
        "intended_use": "AI-assisted quantification of HER2 immunohistochemistry for breast cancer therapy selection.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU", "US"]},
        "sources": [src("https://www.aiforia.com/")],
    },
    {
        "id": "roche-upath-her2-breast",
        "product_name": "uPath HER2 (4B5) image analysis for breast cancer",
        "company": "Roche Diagnostics",
        "company_url": "https://diagnostics.roche.com/",
        "cancer_types": ["breast"],
        "modality": "histopathology",
        "intended_use": "FDA-cleared digital pathology algorithm for quantification of HER2 (4B5) immunohistochemistry on breast cancer tissue sections.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://diagnostics.roche.com/us/en/products/instruments/upath-enterprise-software.html"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "mindpeak-pdl1",
        "product_name": "Mindpeak PD-L1 Lung",
        "company": "Mindpeak",
        "company_url": "https://www.mindpeak.ai/",
        "cancer_types": ["lung"],
        "modality": "histopathology",
        "intended_use": "AI-assisted PD-L1 tumor proportion score quantification on lung cancer tissue sections.",
        "regulatory": {
            "fda_status": "CE IVD",
            "fda_pathway": "ldt",
            "ldt": True,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU", "US"]},
        "sources": [src("https://www.mindpeak.ai/")],
    },
    {
        "id": "owkin-rlapsrisk-bc",
        "product_name": "RlapsRisk BC",
        "company": "Owkin",
        "company_url": "https://www.owkin.com/",
        "cancer_types": ["breast"],
        "modality": "histopathology",
        "intended_use": "AI-based breast cancer recurrence risk prediction from H&E whole-slide images to support adjuvant therapy decisions.",
        "regulatory": {
            "fda_status": "Research Use",
            "fda_pathway": "research_use",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU"]},
        "sources": [src("https://www.owkin.com/diagnostics/rlapsrisk-bc")],
    },
    {
        "id": "stratipath-breast",
        "product_name": "Stratipath Breast",
        "company": "Stratipath",
        "company_url": "https://stratipath.com/",
        "cancer_types": ["breast"],
        "modality": "histopathology",
        "intended_use": "AI-based image analysis for risk stratification of early-stage estrogen-receptor-positive breast cancer from standard H&E slides.",
        "regulatory": {
            "fda_status": "Research Use",
            "fda_pathway": "research_use",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU"]},
        "sources": [src("https://stratipath.com/")],
    },
    {
        "id": "visiopharm-her2-connect",
        "product_name": "HER2-CONNECT",
        "company": "Visiopharm",
        "company_url": "https://visiopharm.com/",
        "cancer_types": ["breast"],
        "modality": "histopathology",
        "intended_use": "CE-IVD image analysis application for HER2 immunohistochemistry quantification in breast cancer tissue sections.",
        "regulatory": {
            "fda_status": "CE IVD",
            "fda_pathway": "ldt",
            "ldt": True,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU"]},
        "sources": [src("https://visiopharm.com/app-center/app/her2-connect/")],
    },
    {
        "id": "ibex-galen-gastric-colon",
        "product_name": "Galen Colon",
        "company": "Ibex Medical Analytics",
        "company_url": "https://ibex-ai.com/",
        "cancer_types": ["colorectal"],
        "modality": "histopathology",
        "intended_use": "AI-based detection of colorectal cancer and polyp features on H&E whole-slide images.",
        "regulatory": {
            "fda_status": "Research Use",
            "fda_pathway": "research_use",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU"]},
        "sources": [src("https://ibex-ai.com/solutions/")],
    },

    # ---------- Radiology: lung / CT ----------
    {
        "id": "optellum-virtual-nodule-clinic",
        "product_name": "Virtual Nodule Clinic (LCP CNN)",
        "company": "Optellum",
        "company_url": "https://www.optellum.com/",
        "cancer_types": ["lung"],
        "modality": "radiology_ct",
        "intended_use": "FDA-authorized AI risk score for indeterminate pulmonary nodules on chest CT to support lung cancer diagnostic workup decisions.",
        "regulatory": {
            "fda_status": "De Novo authorized",
            "fda_pathway": "de_novo",
            "fda_decision_date": "2021-10",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "UK"]},
        "sources": [src("https://www.optellum.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "vuno-med-lungct-ai",
        "product_name": "VUNO Med-LungCT AI",
        "company": "VUNO",
        "company_url": "https://www.vuno.co/en/",
        "cancer_types": ["lung"],
        "modality": "radiology_ct",
        "intended_use": "AI-based detection and characterization of pulmonary nodules on low-dose and diagnostic chest CT.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "KR", "EU"]},
        "sources": [src("https://www.vuno.co/en/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "infervision-inferread-lung-ct",
        "product_name": "InferRead Lung CT.AI",
        "company": "Infervision",
        "company_url": "https://global.infervision.com/",
        "cancer_types": ["lung"],
        "modality": "radiology_ct",
        "intended_use": "AI-based detection, characterization, and longitudinal follow-up of pulmonary nodules on chest CT.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU", "CN"]},
        "sources": [src("https://global.infervision.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "siemens-ai-rad-chest-ct-oncology",
        "product_name": "AI-Rad Companion Chest CT (Oncology)",
        "company": "Siemens Healthineers",
        "company_url": "https://www.siemens-healthineers.com/",
        "cancer_types": ["lung"],
        "modality": "radiology_ct",
        "intended_use": "FDA-cleared AI assistance for quantification and characterization of pulmonary nodules and lung lesions on chest CT.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.siemens-healthineers.com/digital-health-solutions/digital-solutions-overview/clinical-decision-support/ai-rad-companion"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "ge-lung-vcar",
        "product_name": "Lung VCAR",
        "company": "GE HealthCare",
        "company_url": "https://www.gehealthcare.com/",
        "cancer_types": ["lung"],
        "modality": "radiology_ct",
        "intended_use": "AI-assisted detection, quantification, and volumetric follow-up of pulmonary nodules on chest CT.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.gehealthcare.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "aidoc-briefcase-lung-nodule",
        "product_name": "BriefCase — Incidental Lung Nodule",
        "company": "Aidoc",
        "company_url": "https://www.aidoc.com/",
        "cancer_types": ["lung"],
        "modality": "radiology_ct",
        "intended_use": "AI-based flagging of incidental pulmonary nodules on routine non-screening chest and body CT imaging.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.aidoc.com/solutions/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "oxipit-chesteye",
        "product_name": "ChestEye",
        "company": "Oxipit",
        "company_url": "https://oxipit.ai/",
        "cancer_types": ["lung"],
        "modality": "radiology_cxr",
        "intended_use": "AI-based preliminary report generation and abnormality flagging on chest radiographs, including detection of suspicious nodules and masses.",
        "regulatory": {
            "fda_status": "CE IVD",
            "fda_pathway": "research_use",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["EU"]},
        "sources": [src("https://oxipit.ai/products/chesteye/")],
    },

    # ---------- GI endoscopy (CADe polyp detection) ----------
    {
        "id": "medtronic-gi-genius",
        "product_name": "GI Genius",
        "company": "Medtronic",
        "company_url": "https://www.medtronic.com/",
        "cancer_types": ["colorectal"],
        "modality": "radiology_ct",
        "intended_use": "FDA-authorized AI-based computer-assisted detection (CADe) of colonic mucosal lesions suspicious for polyps during real-time colonoscopy.",
        "regulatory": {
            "fda_status": "De Novo authorized",
            "fda_pathway": "de_novo",
            "fda_decision_date": "2021-04",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {
            "key_publication": "Artificial Intelligence and Colonoscopy Experience: Lessons from Two Randomised Trials",
            "journal": "Gut",
            "year": 2022,
            "url": "https://gut.bmj.com/content/71/4/757",
        },
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.medtronic.com/covidien/en-us/products/gastrointestinal-artificial-intelligence/gi-genius-intelligent-endoscopy.html"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "iterative-skout",
        "product_name": "SKOUT",
        "company": "Iterative Health",
        "company_url": "https://www.iterative.health/",
        "cancer_types": ["colorectal"],
        "modality": "radiology_ct",
        "intended_use": "FDA-cleared AI-based CADe for real-time polyp detection during colonoscopy.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": "2022-07",
            "ldt": False,
            "ce_marked": False,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.iterative.health/skout"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "magentiq-colo",
        "product_name": "Magentiq-Colo",
        "company": "Magentiq Eye",
        "company_url": "https://magentiq.com/",
        "cancer_types": ["colorectal"],
        "modality": "radiology_ct",
        "intended_use": "AI-based CADe for real-time polyp detection during colonoscopy.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://magentiq.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "fujifilm-cad-eye",
        "product_name": "CAD EYE",
        "company": "Fujifilm Healthcare",
        "company_url": "https://www.fujifilm.com/",
        "cancer_types": ["colorectal"],
        "modality": "radiology_ct",
        "intended_use": "AI-based real-time CADe and CADx for colorectal polyps and lesion characterization during endoscopy.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU", "JP"]},
        "sources": [src("https://www.fujifilm.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },

    # ---------- Mammography / breast imaging ----------
    {
        "id": "densitas-intellimammo",
        "product_name": "intelliMammo",
        "company": "Densitas",
        "company_url": "https://densitas.health/",
        "cancer_types": ["breast"],
        "modality": "radiology_mammography",
        "intended_use": "AI-based mammographic image quality assessment and breast density quantification.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU", "CA"]},
        "sources": [src("https://densitas.health/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "deephealth-saige-dx",
        "product_name": "Saige-Dx",
        "company": "DeepHealth (RadNet)",
        "company_url": "https://www.deephealth.com/",
        "cancer_types": ["breast"],
        "modality": "radiology_mammography",
        "intended_use": "AI-based concurrent-read assistance for breast cancer detection on 2D digital mammography and digital breast tomosynthesis.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.deephealth.com/"), src(FDA_510K_SEARCH, "fda_db")],
    },

    # ---------- MRI / other imaging ----------
    {
        "id": "subtle-medical-subtlepet",
        "product_name": "SubtlePET",
        "company": "Subtle Medical",
        "company_url": "https://subtlemedical.com/",
        "cancer_types": ["solid_tumor"],
        "modality": "radiology_mri",
        "intended_use": "FDA-cleared deep-learning image enhancement for lower-dose or faster-acquisition PET studies used in oncology imaging.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": "2018-09",
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://subtlemedical.com/subtlepet/"), src(FDA_510K_SEARCH, "fda_db")],
    },

    # ---------- Genomics / molecular ----------
    {
        "id": "myriad-mychoice-cdx",
        "product_name": "myChoice CDx",
        "company": "Myriad Genetics",
        "company_url": "https://myriad.com/",
        "cancer_types": ["ovarian", "breast", "pan_cancer"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "FDA-approved tumor-tissue companion diagnostic for homologous recombination deficiency (HRD) status used to guide PARP inhibitor therapy selection.",
        "regulatory": {
            "fda_status": "PMA approved",
            "fda_pathway": "pma",
            "fda_decision_date": None,
            "ldt": False,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://myriad.com/gene-table/mychoice-cdx/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "myriad-prolaris",
        "product_name": "Prolaris",
        "company": "Myriad Genetics",
        "company_url": "https://myriad.com/",
        "cancer_types": ["prostate"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "Gene expression-based prognostic test for localized prostate cancer providing an individualized disease-aggressiveness score.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://myriad.com/gene-table/prolaris/")],
    },
    {
        "id": "agendia-mammaprint",
        "product_name": "MammaPrint",
        "company": "Agendia",
        "company_url": "https://agendia.com/",
        "cancer_types": ["breast"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "FDA-cleared 70-gene expression signature for recurrence risk stratification in early-stage breast cancer.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": "2007-02",
            "ldt": False,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://agendia.com/mammaprint/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "exact-oncotype-dx-breast",
        "product_name": "Oncotype DX Breast Recurrence Score",
        "company": "Exact Sciences",
        "company_url": "https://www.exactsciences.com/",
        "cancer_types": ["breast"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "21-gene expression assay for recurrence risk and chemotherapy benefit prediction in hormone receptor-positive, HER2-negative early-stage breast cancer.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.exactsciences.com/products/oncotype-dx")],
    },
    {
        "id": "veracyte-prosigna",
        "product_name": "Prosigna (PAM50)",
        "company": "Veracyte",
        "company_url": "https://www.veracyte.com/",
        "cancer_types": ["breast"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "FDA-cleared 50-gene PAM50 assay for intrinsic subtype classification and recurrence risk in post-menopausal early-stage breast cancer.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.veracyte.com/our-tests/prosigna/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "veracyte-envisia",
        "product_name": "Envisia Genomic Classifier",
        "company": "Veracyte",
        "company_url": "https://www.veracyte.com/",
        "cancer_types": ["lung"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "Genomic classifier used in the diagnostic workup of idiopathic pulmonary fibrosis; applied alongside Percepta in pulmonary nodule evaluation workflows.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.veracyte.com/our-tests/envisia/")],
    },
    {
        "id": "tempus-xf",
        "product_name": "Tempus xF (liquid biopsy)",
        "company": "Tempus AI",
        "company_url": "https://www.tempus.com/",
        "cancer_types": ["pan_cancer"],
        "modality": "liquid_biopsy",
        "intended_use": "Tumor-naive liquid biopsy assay providing genomic profiling from circulating tumor DNA across solid tumors.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.tempus.com/oncology/genomics/")],
    },
    {
        "id": "tempus-xm",
        "product_name": "Tempus xM (MRD)",
        "company": "Tempus AI",
        "company_url": "https://www.tempus.com/",
        "cancer_types": ["pan_cancer"],
        "modality": "liquid_biopsy",
        "intended_use": "Minimal residual disease (MRD) monitoring assay from circulating tumor DNA for treated solid tumor patients.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.tempus.com/oncology/genomics/")],
    },
    {
        "id": "natera-altera",
        "product_name": "Altera",
        "company": "Natera",
        "company_url": "https://www.natera.com/",
        "cancer_types": ["pan_cancer"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "Whole-exome sequencing-based tumor profiling used alongside Signatera for personalized MRD monitoring in solid tumors.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.natera.com/oncology/altera/")],
    },

    # ---------- CRC / MCED / screening ----------
    {
        "id": "exact-cologuard-plus",
        "product_name": "Cologuard Plus",
        "company": "Exact Sciences",
        "company_url": "https://www.exactsciences.com/",
        "cancer_types": ["colorectal"],
        "modality": "multiomics",
        "intended_use": "FDA-approved non-invasive stool-based DNA and hemoglobin test for colorectal cancer screening in average-risk adults.",
        "regulatory": {
            "fda_status": "PMA approved",
            "fda_pathway": "pma",
            "fda_decision_date": "2024-10",
            "ldt": False,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.exactsciences.com/products/cologuard"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "guardant-shield",
        "product_name": "Shield",
        "company": "Guardant Health",
        "company_url": "https://guardanthealth.com/",
        "cancer_types": ["colorectal"],
        "modality": "liquid_biopsy",
        "intended_use": "FDA-approved blood-based colorectal cancer screening test for average-risk adults.",
        "regulatory": {
            "fda_status": "PMA approved",
            "fda_pathway": "pma",
            "fda_decision_date": "2024-07",
            "ldt": False,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://guardanthealth.com/shield/"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "freenome-crc-blood-test",
        "product_name": "Freenome CRC Blood Test",
        "company": "Freenome",
        "company_url": "https://www.freenome.com/",
        "cancer_types": ["colorectal"],
        "modality": "liquid_biopsy",
        "intended_use": "Multiomics cell-free DNA blood-based colorectal cancer screening assay evaluated in the PREEMPT-CRC pivotal study.",
        "regulatory": {
            "fda_status": "De Novo authorized",
            "fda_pathway": "de_novo",
            "fda_decision_date": None,
            "ldt": False,
            "medicare_coverage": None,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.freenome.com/")],
    },
    {
        "id": "delfi-firstlook-lung",
        "product_name": "FirstLook Lung",
        "company": "Delfi Diagnostics",
        "company_url": "https://delfidiagnostics.com/",
        "cancer_types": ["lung"],
        "modality": "liquid_biopsy",
        "intended_use": "Fragmentomics-based blood test supporting adherence to lung cancer screening in patients eligible for low-dose CT.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://delfidiagnostics.com/firstlook-lung/")],
    },

    # ---------- Cervical / HPV ----------
    {
        "id": "hologic-genius-cervical",
        "product_name": "Genius Digital Diagnostics System (cervical cytology)",
        "company": "Hologic",
        "company_url": "https://www.hologic.com/",
        "cancer_types": ["cervical"],
        "modality": "histopathology",
        "intended_use": "FDA-cleared AI-based digital cytology system to assist the review of cervical cytology slides collected in liquid-based Pap tests.",
        "regulatory": {
            "fda_status": "510(k) cleared",
            "fda_pathway": "510k",
            "fda_decision_date": None,
            "ldt": False,
            "ce_marked": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US", "EU"]},
        "sources": [src("https://www.hologic.com/hologic-products/cytology/genius-digital-diagnostics-system"), src(FDA_510K_SEARCH, "fda_db")],
    },
    {
        "id": "bd-focalpoint-gs",
        "product_name": "FocalPoint GS Imaging System",
        "company": "BD (Becton Dickinson)",
        "company_url": "https://www.bd.com/",
        "cancer_types": ["cervical"],
        "modality": "histopathology",
        "intended_use": "FDA-approved automated image-analysis system for computer-assisted review of cervical cytology slides.",
        "regulatory": {
            "fda_status": "PMA approved",
            "fda_pathway": "pma",
            "fda_decision_date": None,
            "ldt": False,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://www.bd.com/en-us/offerings/capabilities/cervical-cancer-screening"), src(FDA_510K_SEARCH, "fda_db")],
    },

    # ---------- Dermatology / melanoma ----------
    {
        "id": "castle-decisiondx-melanoma",
        "product_name": "DecisionDx-Melanoma",
        "company": "Castle Biosciences",
        "company_url": "https://castlebiosciences.com/",
        "cancer_types": ["melanoma"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "31-gene expression profile prognostic test for cutaneous melanoma recurrence and metastasis risk stratification.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://castlebiosciences.com/tests/dxm/")],
    },
    {
        "id": "castle-decisiondx-sqcc",
        "product_name": "DecisionDx-SCC",
        "company": "Castle Biosciences",
        "company_url": "https://castlebiosciences.com/",
        "cancer_types": ["dermatopathology"],
        "modality": "genomic_sequencing_with_ai",
        "intended_use": "40-gene expression profile test for risk stratification of high-risk cutaneous squamous cell carcinoma.",
        "regulatory": {
            "fda_status": "LDT",
            "fda_pathway": "ldt",
            "ldt": True,
            "medicare_coverage": True,
        },
        "clinical_evidence": {"key_publication": None, "journal": None, "year": None, "url": None},
        "deployment": {"available": True, "primary_markets": ["US"]},
        "sources": [src("https://castlebiosciences.com/tests/scc/")],
    },
]


def main():
    data = json.loads(DATA.read_text())
    existing_ids = {e["id"] for e in data["entries"]}

    added = []
    skipped = []
    for e in NEW_ENTRIES:
        if e["id"] in existing_ids:
            skipped.append(e["id"])
            continue
        data["entries"].append(e)
        added.append(e["id"])

    data["last_updated"] = TODAY

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"Added {len(added)} entries. Total now: {len(data['entries'])}")
    if skipped:
        print("Skipped (id already existed):", skipped)


if __name__ == "__main__":
    main()
